/*
-- Query: SELECT * FROM chat.chat
LIMIT 0, 1000

-- Date: 2015-03-04 17:28
*/
INSERT INTO `chat` (`message_id`,`posted_on`,`message`,`topic`,`title`,`uplift`,`subtopic_id`,`iduser`,`picpath`) VALUES (1,'2015-01-21 03:17:41','Read the word and pray..','LifeStyle','Keeping Healthy',0,0,1,'propic/propic.gif');
INSERT INTO `chat` (`message_id`,`posted_on`,`message`,`topic`,`title`,`uplift`,`subtopic_id`,`iduser`,`picpath`) VALUES (6,'2015-01-15 03:44:22','God Loves You','Love','john3:16',0,0,1,'propic/propic.gif');
INSERT INTO `chat` (`message_id`,`posted_on`,`message`,`topic`,`title`,`uplift`,`subtopic_id`,`iduser`,`picpath`) VALUES (16,'2015-01-22 01:23:35','oh:3:17: For God sent not his Son into the world to condemn the world; but that the world through him might be saved. Joh:3:18: He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God. Joh:3:19: And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil. Joh:3:20: For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved. Joh:3:21: But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God. Joh:3:22: After these things came Jesus and his disciples into the land of Judaea; and there he tarried with them, and baptized. Joh:3:23: And John also was baptizing in Aenon near to Salim, because there was much water there: and they came, and were baptized. Joh:3:24: For John was not yet cast into prison. Joh:3:25: Then there arose a question between some of John\'s disciples and the Jews about purifying. Joh:3:26: And they came unto John, and said unto him, Rabbi, he that was with thee beyond Jordan, to whom thou barest witness, behold, the same baptizeth, and all men come to him. Joh:3:27: John answered and said, A man can receive nothing, except it be given him from heaven. Joh:3:28: Ye yourselves bear me witness, that I said, I am not the Christ, but that I am sent before him. Joh:3:29: He that hath the bride is the bridegroom: but the friend of the bridegroom, which standeth and heareth him, rejoiceth greatly because of the bridegroom\'s voice: this my joy therefore is fulfilled. Joh:3:30: He must increase, but I must decrease. Joh:3:31: He that cometh from above is above all: he that is of the earth is earthly, and speaketh of the earth: he that cometh from heaven is above all. Joh:3:32: And what he hath seen and heard, that he testifieth; and no man receiveth his testimony. Joh:3:33: He that hath received his testimony hath set to his seal that God is true. Joh:3:34: For he whom God hath sent speaketh the words of God: for God giveth not the Spirit by measure unto him. Joh:3:35: The Father loveth the Son, and hath given all things into his hand. Joh:3:36: He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him.  ','Love','JOHN',0,0,1,'propic/propic.gif');
INSERT INTO `chat` (`message_id`,`posted_on`,`message`,`topic`,`title`,`uplift`,`subtopic_id`,`iduser`,`picpath`) VALUES (17,'2015-01-22 01:39:30','Ro:8:6: For to be carnally minded is death; but to be spiritually minded is life and peace. Ro:8:7: Because the carnal mind is enmity against God: for it is not subject to the law of God, neither indeed can be. Ro:8:8: So then they that are in the flesh cannot please God. Ro:8:9: But ye are not in the flesh, but in the Spirit, if so be that the Spirit of God dwell in you. Now if any man have not the Spirit of Christ, he is none of his. Ro:8:10: And if Christ be in you, the body is dead because of sin; but the Spirit is life because of righteousness.','Grace','ROMANS',6,0,1,'propic/propic.gif');
INSERT INTO `chat` (`message_id`,`posted_on`,`message`,`topic`,`title`,`uplift`,`subtopic_id`,`iduser`,`picpath`) VALUES (45,'2015-03-02 20:12:16','','Mercy','Give Mercy',0,0,1,'\"blank\"');
INSERT INTO `chat` (`message_id`,`posted_on`,`message`,`topic`,`title`,`uplift`,`subtopic_id`,`iduser`,`picpath`) VALUES (46,'2015-03-02 22:45:10','https://www.youtube.com/watch?v=BVpLCnpuUYA','Gospel','The Gospel',0,0,1,'\"blank\"');
INSERT INTO `chat` (`message_id`,`posted_on`,`message`,`topic`,`title`,`uplift`,`subtopic_id`,`iduser`,`picpath`) VALUES (48,'2015-03-02 23:30:34','https://www.youtube.com/watch?v=b-8DpZgY3ek','Gospel','Animated Gospel',0,0,1,'\"blank\"');
